"""
generate_data.py
-----------------
Generates realistic (but intentionally messy) e-commerce datasets for the
E-Commerce Order Analytics System.

Produces four CSV files inside data/raw/:
    customers.csv
    products.csv
    orders.csv
    order_items.csv

Intentional data quality issues are injected on purpose so that the
cleaning and validation scripts (clean_data.py) have real problems to
detect and fix. This mirrors what happens with real-world raw data feeds.

Referential integrity strategy
-------------------------------
1. customers.csv and products.csv are generated first, so their IDs exist
   before anything references them.
2. orders.csv references customers.customer_id. Roughly 5% of orders get a
   missing (NULL/empty) customer_id on purpose - this is realistic because
   guest checkouts or broken tracking often lose the customer reference.
3. order_items.csv references orders.order_id and products.product_id.
   The vast majority of order_items are generated by picking a REAL,
   already-existing order_id from the orders table, which guarantees
   referential integrity for the "valid" bulk of the data.
   A small, controlled number of rows (about 1%) are then given a fake,
   non-existent order_id so that check_referential_integrity() in
   clean_data.py has genuine orphan rows to catch.

Run:
    python scripts/generate_data.py
"""

import csv
import random
from datetime import datetime, timedelta
from pathlib import Path

from faker import Faker

fake = Faker()
Faker.seed(42)
random.seed(42)

# ----------------------------------------------------------------------
# Paths (relative to project root, works on Windows/Mac/Linux via pathlib)
# ----------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = PROJECT_ROOT / "data" / "raw"
RAW_DIR.mkdir(parents=True, exist_ok=True)

# ----------------------------------------------------------------------
# Config
# ----------------------------------------------------------------------
NUM_CUSTOMERS = 600
NUM_PRODUCTS = 550
NUM_ORDERS = 1500
NUM_ORDER_ITEMS = 3000

CUSTOMER_TYPES = ["REGULAR", "PREMIUM", "VIP"]
CUSTOMER_TYPE_WEIGHTS = [0.6, 0.3, 0.1]

CATEGORIES = {
    "Electronics": ["Mobiles", "Laptops", "Accessories", "Cameras", "Audio"],
    "Clothing": ["Men", "Women", "Kids", "Footwear", "Winterwear"],
    "Home": ["Kitchen", "Furniture", "Decor", "Bedding", "Storage"],
    "Books": ["Fiction", "Non-Fiction", "Academic", "Comics", "Children"],
}

ORDER_STATUSES = ["PLACED", "SHIPPED", "DELIVERED", "CANCELLED", "RETURNED"]
ORDER_STATUS_WEIGHTS = [0.15, 0.20, 0.45, 0.10, 0.10]

REGION_CODES = ["NORTH", "SOUTH", "EAST", "WEST", "CENTRAL"]


def make_invalid_email(name: str) -> str:
    """Return one of several deliberately broken email formats."""
    username = name.lower().replace(" ", ".")
    broken_formats = [
        username,  # no @ or domain at all, e.g. "abc"
        f"{username}@",  # missing domain
        "example.com",  # no username/@ at all
        f"{username}example.com",  # missing @
    ]
    return random.choice(broken_formats)


def generate_customers() -> list:
    """Generate customers.csv rows with ~2% invalid emails and some
    duplicate customer records (simulating duplicate signups/imports)."""
    customers = []
    for cust_id in range(1, NUM_CUSTOMERS + 1):
        name = fake.name()
        is_invalid_email = random.random() < 0.02  # ~2% invalid emails
        email = make_invalid_email(name) if is_invalid_email else fake.email()
        reg_date = fake.date_between(start_date="-3y", end_date="today")
        customer_type = random.choices(CUSTOMER_TYPES, weights=CUSTOMER_TYPE_WEIGHTS, k=1)[0]

        customers.append(
            {
                "customer_id": cust_id,
                "customer_name": name,
                "email": email,
                "registration_date": reg_date.strftime("%Y-%m-%d"),
                "customer_type": customer_type,
            }
        )

    # Inject a handful of duplicate customer records (same person, new row,
    # new customer_id) to simulate duplicate signups from a broken form.
    num_duplicates = int(NUM_CUSTOMERS * 0.015)
    for _ in range(num_duplicates):
        original = random.choice(customers[:NUM_CUSTOMERS])
        dup_id = len(customers) + 1
        duplicate = original.copy()
        duplicate["customer_id"] = dup_id
        customers.append(duplicate)

    return customers


def generate_products() -> list:
    """Generate products.csv rows with messy names (extra spaces, mixed case)."""
    products = []
    for prod_id in range(1, NUM_PRODUCTS + 1):
        category = random.choice(list(CATEGORIES.keys()))
        subcategory = random.choice(CATEGORIES[category])
        base_name = f"{fake.word().capitalize()} {subcategory[:-1] if subcategory.endswith('s') else subcategory}"

        # Introduce messy formatting for ~15% of product names
        messy_roll = random.random()
        if messy_roll < 0.07:
            product_name = f"  {base_name}  "  # extra spaces
        elif messy_roll < 0.15:
            product_name = base_name.upper()  # mixed/odd case
        else:
            product_name = base_name

        cost_price = round(random.uniform(5, 2000), 2)

        products.append(
            {
                "product_id": prod_id,
                "product_name": product_name,
                "category": category,
                "subcategory": subcategory,
                "cost_price": cost_price,
            }
        )
    return products


def generate_orders(customer_ids: list) -> list:
    """Generate orders.csv rows.

    ~5% of rows get a NULL/empty customer_id.
    Some order_date values are written in DD-MM-YYYY format instead of the
    standard YYYY-MM-DD HH:MM:SS to simulate a bad upstream export.
    A few realistic "future" dates are added for edge-case testing.
    """
    orders = []
    today = datetime.now()

    for order_id in range(1, NUM_ORDERS + 1):
        # ~5% missing customer_id
        if random.random() < 0.05:
            customer_id = ""
        else:
            customer_id = random.choice(customer_ids)

        # Most dates are in the last 2 years; a small % are in the future
        if random.random() < 0.02:
            order_dt = today + timedelta(days=random.randint(1, 60))
        else:
            order_dt = fake.date_time_between(start_date="-2y", end_date="now")

        # ~8% of dates are written in the wrong format (DD-MM-YYYY, no time)
        if random.random() < 0.08:
            order_date_str = order_dt.strftime("%d-%m-%Y")
        else:
            order_date_str = order_dt.strftime("%Y-%m-%d %H:%M:%S")

        status = random.choices(ORDER_STATUSES, weights=ORDER_STATUS_WEIGHTS, k=1)[0]
        region_code = random.choice(REGION_CODES)

        orders.append(
            {
                "order_id": order_id,
                "customer_id": customer_id,
                "order_date": order_date_str,
                "status": status,
                "region_code": region_code,
            }
        )
    return orders


def generate_order_items(valid_order_ids: list, product_ids: list) -> list:
    """Generate order_items.csv rows.

    The majority of rows reference a REAL order_id (guaranteeing referential
    integrity). A small, controlled number of rows are given a fake
    non-existent order_id so check_referential_integrity() has real orphan
    rows to detect and report.
    """
    order_items = []
    max_real_order_id = max(valid_order_ids)

    # How many rows should intentionally have a broken order_id reference
    num_invalid_refs = max(1, int(NUM_ORDER_ITEMS * 0.01))
    invalid_ref_positions = set(random.sample(range(NUM_ORDER_ITEMS), num_invalid_refs))

    for i in range(NUM_ORDER_ITEMS):
        order_item_id = i + 1

        if i in invalid_ref_positions:
            # Intentionally invalid: an order_id that does NOT exist in orders.csv
            order_id = max_real_order_id + random.randint(1000, 9000)
        else:
            # Valid: pick a real, existing order_id
            order_id = random.choice(valid_order_ids)

        product_id = random.choice(product_ids)

        # ~3% negative quantity to represent returns
        if random.random() < 0.03:
            quantity = -random.randint(1, 5)
        elif random.random() < 0.01:
            quantity = 0  # rare zero-quantity edge case
        else:
            quantity = random.randint(1, 8)

        unit_price = round(random.uniform(5, 2500), 2)

        # discount_percent normally 0-100; a rare invalid outlier > 100
        if random.random() < 0.005:
            discount_percent = round(random.uniform(101, 150), 2)
        else:
            discount_percent = round(random.uniform(0, 60), 2)

        order_items.append(
            {
                "order_item_id": order_item_id,
                "order_id": order_id,
                "product_id": product_id,
                "quantity": quantity,
                "unit_price": unit_price,
                "discount_percent": discount_percent,
            }
        )
    return order_items


def write_csv(rows: list, filepath: Path, fieldnames: list) -> None:
    with open(filepath, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    print(f"Wrote {len(rows):,} rows -> {filepath.relative_to(PROJECT_ROOT)}")


def main():
    print("Generating E-Commerce Order Analytics System raw datasets...\n")

    customers = generate_customers()
    write_csv(
        customers,
        RAW_DIR / "customers.csv",
        ["customer_id", "customer_name", "email", "registration_date", "customer_type"],
    )

    products = generate_products()
    write_csv(
        products,
        RAW_DIR / "products.csv",
        ["product_id", "product_name", "category", "subcategory", "cost_price"],
    )

    customer_ids = [c["customer_id"] for c in customers]
    orders = generate_orders(customer_ids)
    write_csv(
        orders,
        RAW_DIR / "orders.csv",
        ["order_id", "customer_id", "order_date", "status", "region_code"],
    )

    order_ids = [o["order_id"] for o in orders]
    product_ids = [p["product_id"] for p in products]
    order_items = generate_order_items(order_ids, product_ids)
    write_csv(
        order_items,
        RAW_DIR / "order_items.csv",
        ["order_item_id", "order_id", "product_id", "quantity", "unit_price", "discount_percent"],
    )

    print("\nData generation complete. Raw files are in data/raw/")


if __name__ == "__main__":
    main()
